Add package names endpoint
leoafarias/pub_api_client pull request #55
Opened 2024-11-19 17:50 UTC by Rexios80

Built on https://github.com/leoafarias/pub_api_client/pull/54 since this needs recursive paging

2024-12-26 13:07 UTC, leoafarias requested changes

2024-12-26 13:07 UTC, leoafarias commented on lib/src/pub_api_client_base.dart
> -  Future<List<String>> packageNameCompletion() async {
Is this a breaking change? Can you have packageNames, and have packageNameCompletiion deprecated and calling packageNames?

2024-12-26 15:13 UTC, Rexios80 commented on lib/src/pub_api_client_base.dart
> -  Future<List<String>> packageNameCompletion() async {
This method still exists below. The old code was calling the `packageNames` endpoint and calling it `packageNameCompletion`.

2025-01-06 17:43 UTC, Rexios80 commented
@leoafarias Do you need anything from me on this?

2025-01-06 17:44 UTC, merged